// <auto-generated />
namespace Koonlight.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fourthMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fourthMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202111241326374_fourthMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
